# Generated by Django 4.2.13 on 2024-05-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0003_alter_deposit_mtrt_int_alter_saving_mtrt_int'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='depoists',
            field=models.ManyToManyField(blank=True, related_name='users', to='compare.deposit'),
        ),
        migrations.AddField(
            model_name='user',
            name='savings',
            field=models.ManyToManyField(blank=True, related_name='user', to='compare.saving'),
        ),
    ]
