# Generated by Django 4.2.13 on 2024-05-23 11:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.TextField()),
                ('date_time', models.TextField()),
                ('price', models.IntegerField()),
                ('users', models.ManyToManyField(blank=True, related_name='real_estates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
