# Generated by Django 4.2.13 on 2024-05-23 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0002_alter_realestate_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realestate',
            old_name='religion',
            new_name='region',
        ),
    ]
