# Generated by Django 4.2.13 on 2024-05-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='dcls_end_day',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='saving',
            name='dcls_end_day',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
