# Generated by Django 4.2.13 on 2024-05-20 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depositoptions',
            old_name='sava_trm',
            new_name='save_trm',
        ),
        migrations.RenameField(
            model_name='savingoptions',
            old_name='sava_trm',
            new_name='save_trm',
        ),
    ]
