# Generated by Django 4.2.13 on 2024-05-20 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0002_rename_sava_trm_depositoptions_save_trm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='mtrt_int',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saving',
            name='mtrt_int',
            field=models.TextField(blank=True, null=True),
        ),
    ]
